# Generated by Django 5.1.2 on 2024-11-07 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_review_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='matn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product', verbose_name='mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='avtor')),
            ],
            options={
                'verbose_name': 'Izox',
                'verbose_name_plural': 'Izoxlar',
            },
        ),
    ]
